name: start
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  get: any
  intl: ^0.17.0
  http: ^0.13.4
  faker: ^2.0.0
  hexcolor: ^2.0.6
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.14
  google_sign_in: ^5.3.2
  shared_preferences: ^2.0.13
  permission_handler: ^9.2.0
  contacts_service: ^0.6.3
  transparent_image: ^2.0.0
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.5.3+1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/images/pexels/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets\fonts\Roboto\Roboto-Light.ttf
        - asset: assets\fonts\Roboto\Roboto-Thin.ttf
        - asset: assets\fonts\Roboto\Roboto-Regular.ttf
        - asset: assets\fonts\Roboto\Roboto-Medium.ttf
        - asset: assets\fonts\Roboto\Roboto-Bold.ttf
        - asset: assets\fonts\Roboto\Roboto-Black.ttf
    - family: RobotoCondensed
      fonts: 
        - asset: assets\fonts\Roboto\RobotoCondensed-Light.ttf
        - asset: assets\fonts\Roboto\RobotoCondensed-Regular.ttf
        - asset: assets\fonts\Roboto\RobotoCondensed-Bold.ttf
  uses-material-design: true

