name: start
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  get: any
  dio: ^4.0.6
  uuid: ^3.0.6
  intl: ^0.17.0
  http: ^0.13.4
  faker: ^2.0.0
  get_it: ^7.2.0
  chewie: ^1.3.4
  hexcolor: ^2.0.6
  video_player: ^2.4.5
  google_sign_in: ^5.3.2
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.14
  cupertino_icons: ^1.0.2
  contacts_service: ^0.6.3
  cloud_firestore: ^3.1.14
  transparent_image: ^2.0.0
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.13
  firebase_messaging: ^11.4.1
  flutter_local_notifications: ^9.5.3+1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: CustomIcons
      fonts: 
        - asset: assets\fonts\CustomIcons\CustomIcons.ttf
    - family: AndersonGrotesk
      fonts: 
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-Oblique.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-Light.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-LightOblique.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-Bold.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-BoldOblique.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-Ultrabold.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-UltraboldOblique.otf
        - asset: assets\fonts\AndersonGrotesk\AndersonGrotesk-Black.otf
  uses-material-design: true

