// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuBv0K3qpUKMolh7qD5nxnLhuRdOq6Uj0',
    appId: '1:423793512970:web:a8abf058282c4072eb05f3',
    messagingSenderId: '423793512970',
    projectId: 'start-firebase-49b01',
    authDomain: 'start-firebase-49b01.firebaseapp.com',
    databaseURL: 'https://start-firebase-49b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'start-firebase-49b01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbqvLxgZBRDTxwVfsUbIUKndAxBN6tqqY',
    appId: '1:423793512970:android:814e28fa8e813375eb05f3',
    messagingSenderId: '423793512970',
    projectId: 'start-firebase-49b01',
    databaseURL: 'https://start-firebase-49b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'start-firebase-49b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvaW8qCEfFZXWqkxtkL6RJwyP9T8mpObM',
    appId: '1:423793512970:ios:1914572028c82897eb05f3',
    messagingSenderId: '423793512970',
    projectId: 'start-firebase-49b01',
    databaseURL: 'https://start-firebase-49b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'start-firebase-49b01.appspot.com',
    iosClientId: '423793512970-1s5v6kals9746s83e4r9mb2m8irpesh1.apps.googleusercontent.com',
    iosBundleId: 'com.ez',
  );
}
